name: CI Pipeline for FizzBuzz

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      # This step checks out the repository's code onto the runner.

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
      # This step sets up Python 3.10 on the runner.

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      # This step installs dependencies:
      # - Upgrades `pip` to the latest version.
      # - Installs `pytest` for running tests.
      # - Installs dependencies from `requirements.txt` (if it exists).

    - name: Run tests
      run: |
        pytest
      # This step runs the tests using `pytest`.
